### ISSUE TITLE
请教一个问题，廖老师

### ISSUE THREAD

**Issue by Evan1995** [michaelliao/learngit#1892]
请问我在Github上删除了一个分支，但是在电脑上用 git branch -a  的时候还是会显示这个远程分支，请问这该怎么处理？多谢

**Comment by Evan1995** [comment]
![image](https://cloud.githubusercontent.com/assets/13522803/23243810/37f29222-f9bc-11e6-8ed3-e7f11d6dbfa6.png)

**Comment by Evan1995** [comment]
删除在本地有但在远程库中已经不存在的分支

**Comment by xiongmi** [comment]
所以怎么搞呢。。。@Evan1995
