### ISSUE TITLE
Readme 里的工具404

### ISSUE THREAD

**Issue by AndraidAP270868441b4** [michaelliao/learngit#2558]
Gitignore在线生成工具 → https://gitignore.itranswarp.com/
![image](https://github.com/michaelliao/learngit/assets/86146160/37011de8-d116-4279-b94f-3842f8ac52df)

**Comment by michaelliao** [comment]
[michaelliao.github.io/gitignore-online-generator/](https://michaelliao.github.io/gitignore-online-generator/)

**Comment by AndraidAP270868441b4** [comment]
ok
